type StringKey<T> = Extract<keyof T, string>;
type ExtractToUpperCase<S> = S extends Capitalize<S & string> ? S : never;
type GlobalObject = typeof globalThis;
type AnyConsturctor = new (...args: any[]) => any;
type AnyFunc = (...args: any[]) => any;
type GlobalNames<Subtype> = {
  [K in StringKey<GlobalObject>]: GlobalObject[K] extends Subtype ? K : never;
}[StringKey<GlobalObject>];
export type GlobalConstructors = GlobalNames<AnyConsturctor>;
export type GlobalVars = Exclude<GlobalNames<object>, GlobalConstructors>;
export type GlobalConstructorsWithStatic = ExtractToUpperCase<
  {
    [K in GlobalConstructors]: [ValidKey<GlobalObject[K]>] extends [never] ? never : K;
  }[GlobalConstructors]
>;
export type FuncProps = "length" | "name" | "prototype";
const funcProps = new Set(["length", "name", "prototype"]);

export type FilterValidKeys<K extends string> = Exclude<K, FuncProps>;
export type ValidKey<V> = FilterValidKeys<StringKey<V>>;
export type SupportedPlatform = "browser" | "node";
export type FuncKind = `func${"" | "-bind"}`;
export type PropKind = "constant" | "prop";
export type MemberKind = FuncKind | PropKind;

export type ProxyHandleRule = GeneralNode<any>;

export type MembersOf<V> = {
  [P in ValidKey<V>]: V[P] extends AnyFunc ? FuncKind : PropKind;
};

export type ObjectNode<V extends object> = {
  type: "object";
  members: MembersOf<V>;
};
export type ConstructorNode<C extends object> = {
  type: "constructor";
  members: MembersOf<C>;
};

export type FuncNode = {
  type: "func";
  name: string;
};

export type NullNode = "noop";

export type NormalNode<V extends object> = ConstructorNode<V> | FuncNode | ObjectNode<V>;

export type LeafNode<V extends object> = NormalNode<V> | NullNode;

export type PlatformNode<S extends object, N = LeafNode<S>> = {
  type: "platform";
  diffs: Record<SupportedPlatform, N | NullNode>;
};

export type GeneralNode<T extends object> = PlatformNode<T> | LeafNode<T>;

type ExtractGlobalMapWithKeys<Keys extends GlobalNames<any>> = {
  [K in Keys]: GlobalObject[K] extends infer V extends object
    ?
        | NullNode
        | (V extends AnyConsturctor
            ? ConstructorNode<V> | PlatformNode<V, ConstructorNode<V>>
            : K extends Uncapitalize<K>
            ? V extends AnyFunc
              ? FuncNode | PlatformNode<V, FuncNode>
              : V extends object
              ? ObjectNode<V> | PlatformNode<V, ObjectNode<V>>
              : never
            : ObjectNode<V> | PlatformNode<V, ObjectNode<V>>)
    : never;
};
const strKeys = <T extends object>(value: T): Extract<keyof T, string>[] =>
  Object.keys(Object.getOwnPropertyDescriptors(value)) as never;
const validKeys = <T extends object>(value: T): ValidKey<T>[] =>
  strKeys(value).filter((k): k is ValidKey<T> => !funcProps.has(k));
const fromEntries: <K extends string, V>(entries: (readonly [K, V])[]) => Record<K, V> = Object.fromEntries as never;
const getRuleByRuntimeVal = <T extends object>(val: T, mapper: Filter<T>): MembersOf<T> =>
  // @ts-ignore
  fromEntries(validKeys(val).map((key) => [key, mapper(key)]));

const browserOnly = <T extends object, N extends GeneralNode<T>>(node: N): PlatformNode<T, N> => ({
  type: "platform",
  diffs: {
    node: "noop",
    browser: node,
  },
});

const browserFunc = (name: GlobalVars) =>
  browserOnly({
    type: "func",
    name,
  });

// @ts-expect-error Dynamic Implementation
const bf = <K extends GlobalVars>(name: K): Record<K, PlatformNode<AnyFunc, FuncNode>> => ({
  [name]: browserFunc(name),
});

const bo = <K extends GlobalVars>(
  name: K,
  members: MembersOf<GlobalObject[K]>
): Record<K, ObjectNode<GlobalObject[K]>> =>
  // @ts-expect-error Dynamic Implementation
  ({
    [name]: browserOnly({
      type: "object",
      members,
    }),
  });

type Filter<T extends object> = (key: ValidKey<T>) => MemberKind;

const defaultFilter =
  <T extends object>(obj: T) =>
  (k: Exclude<Extract<keyof T, string>, FuncProps>): MemberKind => {
    const { get, set, value } = Object.getOwnPropertyDescriptor(obj, k)!;
    if (get || set) return "prop";
    if (typeof value === "function") return "func";
    return "constant";
  };

const objectNode = <T extends object>(obj: T, filter?: Filter<T>): ObjectNode<T> => ({
  type: "object",
  members: getRuleByRuntimeVal(obj, filter ?? defaultFilter(obj)),
});
// @ts-expect-error Dynamic Implementation
const so = <K extends GlobalVars>(name: K): Record<K, ObjectNode<GlobalObject[K]>> => ({
  [name]: objectNode(globalThis[name]),
});

// @ts-expect-error Dynamic Implementation
const sf = <K extends GlobalVars>(name: K): Record<K, FuncNode> => ({
  [name]: {
    type: "func",
    name,
  },
});

export const globalVars: ExtractGlobalMapWithKeys<GlobalVars> = {
  ...bf("addEventListener"),
  ...bf("alert"),
  ...bf("atob"),
  ...so("Atomics"),
  ...so("BigInt"),
  ...bf("blur"),
  ...sf("btoa"),
  ...bo("caches", {
    delete: "func-bind",
    has: "func-bind",
    keys: "func-bind",
    match: "func-bind",
    open: "func-bind",
  }),
  ...bf("cancelAnimationFrame"),
  ...bf("cancelIdleCallback"),
  ...bf("captureEvents"),
  ...sf("clearImmediate"),
  ...sf("clearInterval"),
  ...sf("clearTimeout"),
  clientInformation: "noop",
  ...bf("close"),
  ...bf("confirm"),
  console: {
    type: "platform",
    diffs: {
      browser: objectNode(console, (k) => (k === "Console" ? "constant" : "func-bind")),
      node: objectNode(console, (k) => (k === "Console" ? "constant" : "func")),
    },
  },
  ...bf("createImageBitmap"),
  crypto: {
    type: "platform",
    diffs: {
      node: "noop",
      browser: {
        type: "object",
        members: {
          subtle: "prop",
          getRandomValues: "func-bind",
          randomUUID: "func-bind",
        },
      },
    },
  },
  ...bo("CSS", {
    escape: "func",
    supports: "func",
  }),
  ...bo("customElements", {
    define: "func-bind",
    get: "func-bind",
    upgrade: "func-bind",
    whenDefined: "func-bind",
  }),
  ...sf("decodeURI"),
  ...sf("decodeURIComponent"),
  ...bf("dispatchEvent"),
  document: "noop",
  ...sf("encodeURI"),
  ...sf("encodeURIComponent"),
  ...sf("escape"),
  ...sf("eval"),
  ...bo("external", {
    AddSearchProvider: "func-bind",
    IsSearchProviderInstalled: "func-bind",
  }),
  ...bf("fetch"),
  ...bf("focus"),
  frames: "noop",
  ...bf("getComputedStyle"),
  ...bf("getSelection"),
  global: "noop",
  ...so("globalThis"),
  ...bo("history", {
    back: "func-bind",
    forward: "func-bind",
    go: "func-bind",
    pushState: "func-bind",
    replaceState: "func-bind",
    scrollRestoration: "prop",
    state: "prop",
  }),
  ...bf("importScripts"),
  ...bo("indexedDB", {
    cmp: "func-bind",
    databases: "func-bind",
    deleteDatabase: "func-bind",
    open: "func-bind",
  }),
  ...so("Intl"),
  ...sf("isFinite"),
  ...sf("isNaN"),
  ...so("JSON"),
  localStorage: "noop",
  location: "noop",
  locationbar: "noop",
  ...bf("matchMedia"),
  ...so("Math"),
  menubar: "noop",
  module: "noop",
  ...bf("moveBy"),
  ...bf("moveTo"),
  navigator: "noop",
  ...bo("NodeFilter", {
    FILTER_ACCEPT: "constant",
    FILTER_REJECT: "constant",
    FILTER_SKIP: "constant",
    SHOW_ALL: "constant",
    SHOW_ATTRIBUTE: "constant",
    SHOW_CDATA_SECTION: "constant",
    SHOW_COMMENT: "constant",
    SHOW_DOCUMENT: "constant",
    SHOW_DOCUMENT_FRAGMENT: "constant",
    SHOW_DOCUMENT_TYPE: "constant",
    SHOW_ELEMENT: "constant",
    SHOW_ENTITY: "constant",
    SHOW_ENTITY_REFERENCE: "constant",
    SHOW_NOTATION: "constant",
    SHOW_PROCESSING_INSTRUCTION: "constant",
    SHOW_TEXT: "constant",
  }),
  ...bf("open"),
  parent: "noop",
  ...bf("parseFloat"),
  ...sf("parseInt"),
  performance: "noop",
  personalbar: "noop",
  ...bf("postMessage"),
  ...bf("print"),
  process: "noop",
  ...bf("prompt"),
  ...sf("queueMicrotask"),
  ...so("Reflect"),
  ...bf("releaseEvents"),
  ...bf("removeEventListener"),
  ...bf("reportError"),
  ...bf("requestAnimationFrame"),
  ...bf("requestIdleCallback"),
  require: "noop",
  ...bf("resizeBy"),
  ...bf("resizeTo"),
  screen: "noop",
  ...bf("scroll"),
  scrollbars: "noop",
  ...bf("scrollBy"),
  ...bf("scrollTo"),
  self: "noop",
  sessionStorage: "noop",
  ...sf("setImmediate"),
  ...sf("setInterval"),
  ...sf("setTimeout"),
  speechSynthesis: "noop",
  statusbar: "noop",
  ...bf("stop"),
  ...bf("structuredClone"),
  ...so("Symbol"),
  toolbar: "noop",
  ...sf("toString"),
  ...sf("unescape"),
  ...so("WebAssembly"),
  window: "noop",
  WScript: "noop",
  WSH: "noop",
};
export const isGlobalVar = (name: string): name is GlobalVars => {
  return name in globalVars;
};

const ctorNode = <K extends GlobalConstructors>(
  members: MembersOf<GlobalObject[K]>
): ConstructorNode<GlobalObject[K]> => ({
  type: "constructor",
  members,
});

const sc = <K extends GlobalConstructors>(
  name: K,
  filter?: Filter<GlobalObject[K]>
): Record<K, ConstructorNode<GlobalObject[K]>> =>
  // @ts-expect-error Dynamic Implementation
  ({
    [name]: ctorNode<K>(getRuleByRuntimeVal(globalThis[name], filter ?? defaultFilter(globalThis[name]))),
  });

const bc = <K extends GlobalConstructors>(
  name: K,
  members: MembersOf<GlobalObject[K]>
): Record<K, PlatformNode<GlobalObject[K], ConstructorNode<GlobalObject[K]>>> =>
  // @ts-expect-error Dynamic Implementation
  ({
    [name]: browserOnly(ctorNode<K>(members)),
  });

//*
export const globalConstructorWithStatics: ExtractGlobalMapWithKeys<GlobalConstructorsWithStatic> = {
  ...sc("Array"),
  ...sc("ArrayBuffer"),
  ...sc("BigInt64Array"),
  ...sc("BigUint64Array"),
  Buffer: {
    type: "platform",
    diffs: {
      browser: "noop",
      node: ctorNode(getRuleByRuntimeVal(Buffer, defaultFilter(Buffer))),
    },
  },
  ...bc("CSSRule", {
    CHARSET_RULE: "constant",
    FONT_FACE_RULE: "constant",
    IMPORT_RULE: "constant",
    KEYFRAME_RULE: "constant",
    KEYFRAMES_RULE: "constant",
    MEDIA_RULE: "constant",
    NAMESPACE_RULE: "constant",
    PAGE_RULE: "constant",
    STYLE_RULE: "constant",
    SUPPORTS_RULE: "constant",
  }),
  Date: "noop",
  ...bc("DOMException", {
    ABORT_ERR: "constant",
    DATA_CLONE_ERR: "constant",
    DOMSTRING_SIZE_ERR: "constant",
    HIERARCHY_REQUEST_ERR: "constant",
    INDEX_SIZE_ERR: "constant",
    INUSE_ATTRIBUTE_ERR: "constant",
    INVALID_ACCESS_ERR: "constant",
    INVALID_CHARACTER_ERR: "constant",
    INVALID_MODIFICATION_ERR: "constant",
    INVALID_NODE_TYPE_ERR: "constant",
    INVALID_STATE_ERR: "constant",
    NAMESPACE_ERR: "constant",
    NETWORK_ERR: "constant",
    NO_DATA_ALLOWED_ERR: "constant",
    NO_MODIFICATION_ALLOWED_ERR: "constant",
    NOT_FOUND_ERR: "constant",
    NOT_SUPPORTED_ERR: "constant",
    QUOTA_EXCEEDED_ERR: "constant",
    SECURITY_ERR: "constant",
    SYNTAX_ERR: "constant",
    TIMEOUT_ERR: "constant",
    TYPE_MISMATCH_ERR: "constant",
    URL_MISMATCH_ERR: "constant",
    VALIDATION_ERR: "constant",
    WRONG_DOCUMENT_ERR: "constant",
  }),
  ...bc("DOMMatrix", {
    fromFloat32Array: "func",
    fromFloat64Array: "func",
    fromMatrix: "func",
  }),
  ...bc("DOMMatrixReadOnly", {
    fromFloat32Array: "func",
    fromFloat64Array: "func",
    fromMatrix: "func",
    // TypeScript has this definition, but it seems to be inheritered form `Function.prototype`.
    toString: "func-bind",
  }),
  ...bc("DOMPoint", {
    fromPoint: "func",
  }),
  ...bc("DOMPointReadOnly", {
    fromPoint: "func",
  }),
  ...bc("DOMQuad", {
    fromQuad: "func",
    fromRect: "func",
  }),
  ...bc("DOMRect", {
    fromRect: "func",
  }),
  ...bc("DOMRectReadOnly", {
    fromRect: "func",
  }),
  Error: "noop",
  EvalError: "noop",
  Event: "noop",
  ...bc("EventSource", {
    CLOSED: "constant",
    CONNECTING: "constant",
    OPEN: "constant",
  }),
  ...bc("FileReader", {
    DONE: "constant",
    EMPTY: "constant",
    LOADING: "constant",
  }),
  Float32Array: "noop",
  Float64Array: "noop",
  ...bc("GeolocationPositionError", {
    PERMISSION_DENIED: "constant",
    POSITION_UNAVAILABLE: "constant",
    TIMEOUT: "constant",
  }),
  ...bc("HTMLMediaElement", {
    HAVE_CURRENT_DATA: "constant",
    HAVE_ENOUGH_DATA: "constant",
    HAVE_FUTURE_DATA: "constant",
    HAVE_METADATA: "constant",
    HAVE_NOTHING: "constant",
    NETWORK_EMPTY: "constant",
    NETWORK_IDLE: "constant",
    NETWORK_LOADING: "constant",
    NETWORK_NO_SOURCE: "constant",
  }),
  ...bc("HTMLScriptElement", {
    supports: "func",
  }),
  ...bc("HTMLTrackElement", {
    ERROR: "constant",
    LOADED: "constant",
    LOADING: "constant",
    NONE: "constant",
  }),
  ...bc("IDBKeyRange", {
    bound: "func",
    lowerBound: "func",
    only: "func",
    upperBound: "func",
  }),
  ...sc("Int16Array"),
  ...sc("Int32Array"),
  ...sc("Int8Array"),
  ...bc("KeyboardEvent", {
    DOM_KEY_LOCATION_LEFT: "constant",
    DOM_KEY_LOCATION_NUMPAD: "constant",
    DOM_KEY_LOCATION_RIGHT: "constant",
    DOM_KEY_LOCATION_STANDARD: "constant",
  }),
  ...bc("MediaError", {
    MEDIA_ERR_ABORTED: "constant",
    MEDIA_ERR_DECODE: "constant",
    MEDIA_ERR_NETWORK: "constant",
    MEDIA_ERR_SRC_NOT_SUPPORTED: "constant",
  }),
  ...bc("MediaRecorder", {
    isTypeSupported: "func",
  }),
  ...bc("MediaSource", {
    isTypeSupported: "func",
  }),
  ...bc("MutationEvent", {
    ADDITION: "constant",
    MODIFICATION: "constant",
    REMOVAL: "constant",
  }),
  ...bc("Node", {
    ATTRIBUTE_NODE: "constant",
    CDATA_SECTION_NODE: "constant",
    COMMENT_NODE: "constant",
    DOCUMENT_FRAGMENT_NODE: "constant",
    DOCUMENT_NODE: "constant",
    DOCUMENT_POSITION_CONTAINED_BY: "constant",
    DOCUMENT_POSITION_CONTAINS: "constant",
    DOCUMENT_POSITION_DISCONNECTED: "constant",
    DOCUMENT_POSITION_FOLLOWING: "constant",
    DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC: "constant",
    DOCUMENT_POSITION_PRECEDING: "constant",
    DOCUMENT_TYPE_NODE: "constant",
    ELEMENT_NODE: "constant",
    ENTITY_NODE: "constant",
    ENTITY_REFERENCE_NODE: "constant",
    NOTATION_NODE: "constant",
    PROCESSING_INSTRUCTION_NODE: "constant",
    TEXT_NODE: "constant",
  }),
  ...bc("Notification", {
    permission: "prop",
    requestPermission: "func",
  }),
  ...sc("Number"),
  ...sc("Object"),
  ...bc("PerformanceNavigation", {
    TYPE_BACK_FORWARD: "constant",
    TYPE_NAVIGATE: "constant",
    TYPE_RELOAD: "constant",
    TYPE_RESERVED: "constant",
  }),
  ...bc("PerformanceObserver", {
    supportedEntryTypes: "prop",
  }),
  Promise: "noop",
  Proxy: "noop",
  ...bc("PublicKeyCredential", {
    isUserVerifyingPlatformAuthenticatorAvailable: "func",
  }),
  ...bc("PushManager", {
    supportedContentEncodings: "prop",
  }),
  ...bc("Range", {
    END_TO_END: "constant",
    END_TO_START: "constant",
    START_TO_END: "constant",
    START_TO_START: "constant",
    // TypeScript has this definition, but it seems to be inheritered form `Function.prototype`.
    toString: "func-bind",
  }),
  RangeError: "noop",
  ReferenceError: "noop",
  RegExp: "noop",
  ...bc("Response", {
    error: "func",
    redirect: "func",
  }),
  ...bc("RTCPeerConnection", {
    generateCertificate: "func",
  }),
  ...bc("RTCRtpReceiver", {
    getCapabilities: "func",
  }),
  ...bc("RTCRtpSender", {
    getCapabilities: "func",
  }),
  ...bc("Selection", {
    // TypeScript has this definition, but it seems to be inheritered form `Function.prototype`.
    toString: "func-bind",
  }),
  ...sc("String"),
  ...bc("SVGAngle", {
    SVG_ANGLETYPE_DEG: "constant",
    SVG_ANGLETYPE_GRAD: "constant",
    SVG_ANGLETYPE_RAD: "constant",
    SVG_ANGLETYPE_UNKNOWN: "constant",
    SVG_ANGLETYPE_UNSPECIFIED: "constant",
  }),
  ...bc("SVGComponentTransferFunctionElement", {
    SVG_FECOMPONENTTRANSFER_TYPE_DISCRETE: "constant",
    SVG_FECOMPONENTTRANSFER_TYPE_GAMMA: "constant",
    SVG_FECOMPONENTTRANSFER_TYPE_IDENTITY: "constant",
    SVG_FECOMPONENTTRANSFER_TYPE_LINEAR: "constant",
    SVG_FECOMPONENTTRANSFER_TYPE_TABLE: "constant",
    SVG_FECOMPONENTTRANSFER_TYPE_UNKNOWN: "constant",
  }),
  ...bc("SVGFEBlendElement", {
    SVG_FEBLEND_MODE_COLOR: "constant",
    SVG_FEBLEND_MODE_COLOR_BURN: "constant",
    SVG_FEBLEND_MODE_COLOR_DODGE: "constant",
    SVG_FEBLEND_MODE_DARKEN: "constant",
    SVG_FEBLEND_MODE_DIFFERENCE: "constant",
    SVG_FEBLEND_MODE_EXCLUSION: "constant",
    SVG_FEBLEND_MODE_HARD_LIGHT: "constant",
    SVG_FEBLEND_MODE_HUE: "constant",
    SVG_FEBLEND_MODE_LIGHTEN: "constant",
    SVG_FEBLEND_MODE_LUMINOSITY: "constant",
    SVG_FEBLEND_MODE_MULTIPLY: "constant",
    SVG_FEBLEND_MODE_NORMAL: "constant",
    SVG_FEBLEND_MODE_OVERLAY: "constant",
    SVG_FEBLEND_MODE_SATURATION: "constant",
    SVG_FEBLEND_MODE_SCREEN: "constant",
    SVG_FEBLEND_MODE_SOFT_LIGHT: "constant",
    SVG_FEBLEND_MODE_UNKNOWN: "constant",
  }),
  ...bc("SVGFEColorMatrixElement", {
    SVG_FECOLORMATRIX_TYPE_HUEROTATE: "constant",
    SVG_FECOLORMATRIX_TYPE_LUMINANCETOALPHA: "constant",
    SVG_FECOLORMATRIX_TYPE_MATRIX: "constant",
    SVG_FECOLORMATRIX_TYPE_SATURATE: "constant",
    SVG_FECOLORMATRIX_TYPE_UNKNOWN: "constant",
  }),
  ...bc("SVGFECompositeElement", {
    SVG_FECOMPOSITE_OPERATOR_ARITHMETIC: "constant",
    SVG_FECOMPOSITE_OPERATOR_ATOP: "constant",
    SVG_FECOMPOSITE_OPERATOR_IN: "constant",
    SVG_FECOMPOSITE_OPERATOR_OUT: "constant",
    SVG_FECOMPOSITE_OPERATOR_OVER: "constant",
    SVG_FECOMPOSITE_OPERATOR_UNKNOWN: "constant",
    SVG_FECOMPOSITE_OPERATOR_XOR: "constant",
  }),
  ...bc("SVGFEConvolveMatrixElement", {
    SVG_EDGEMODE_DUPLICATE: "constant",
    SVG_EDGEMODE_NONE: "constant",
    SVG_EDGEMODE_UNKNOWN: "constant",
    SVG_EDGEMODE_WRAP: "constant",
  }),
  ...bc("SVGFEDisplacementMapElement", {
    SVG_CHANNEL_A: "constant",
    SVG_CHANNEL_B: "constant",
    SVG_CHANNEL_G: "constant",
    SVG_CHANNEL_R: "constant",
    SVG_CHANNEL_UNKNOWN: "constant",
  }),
  ...bc("SVGFEMorphologyElement", {
    SVG_MORPHOLOGY_OPERATOR_DILATE: "constant",
    SVG_MORPHOLOGY_OPERATOR_ERODE: "constant",
    SVG_MORPHOLOGY_OPERATOR_UNKNOWN: "constant",
  }),
  ...bc("SVGFETurbulenceElement", {
    SVG_STITCHTYPE_NOSTITCH: "constant",
    SVG_STITCHTYPE_STITCH: "constant",
    SVG_STITCHTYPE_UNKNOWN: "constant",
    SVG_TURBULENCE_TYPE_FRACTALNOISE: "constant",
    SVG_TURBULENCE_TYPE_TURBULENCE: "constant",
    SVG_TURBULENCE_TYPE_UNKNOWN: "constant",
  }),
  ...bc("SVGGradientElement", {
    SVG_SPREADMETHOD_PAD: "constant",
    SVG_SPREADMETHOD_REFLECT: "constant",
    SVG_SPREADMETHOD_REPEAT: "constant",
    SVG_SPREADMETHOD_UNKNOWN: "constant",
  }),
  ...bc("SVGLength", {
    SVG_LENGTHTYPE_CM: "constant",
    SVG_LENGTHTYPE_EMS: "constant",
    SVG_LENGTHTYPE_EXS: "constant",
    SVG_LENGTHTYPE_IN: "constant",
    SVG_LENGTHTYPE_MM: "constant",
    SVG_LENGTHTYPE_NUMBER: "constant",
    SVG_LENGTHTYPE_PC: "constant",
    SVG_LENGTHTYPE_PERCENTAGE: "constant",
    SVG_LENGTHTYPE_PT: "constant",
    SVG_LENGTHTYPE_PX: "constant",
    SVG_LENGTHTYPE_UNKNOWN: "constant",
  }),
  ...bc("SVGMarkerElement", {
    SVG_MARKER_ORIENT_ANGLE: "constant",
    SVG_MARKER_ORIENT_AUTO: "constant",
    SVG_MARKER_ORIENT_UNKNOWN: "constant",
    SVG_MARKERUNITS_STROKEWIDTH: "constant",
    SVG_MARKERUNITS_UNKNOWN: "constant",
    SVG_MARKERUNITS_USERSPACEONUSE: "constant",
  }),
  ...bc("SVGMatrix", {
    fromFloat32Array: "func",
    fromFloat64Array: "func",
    fromMatrix: "func",
  }),
  ...bc("SVGPoint", {
    fromPoint: "func",
  }),
  ...bc("SVGPreserveAspectRatio", {
    SVG_MEETORSLICE_MEET: "constant",
    SVG_MEETORSLICE_SLICE: "constant",
    SVG_MEETORSLICE_UNKNOWN: "constant",
    SVG_PRESERVEASPECTRATIO_NONE: "constant",
    SVG_PRESERVEASPECTRATIO_UNKNOWN: "constant",
    SVG_PRESERVEASPECTRATIO_XMAXYMAX: "constant",
    SVG_PRESERVEASPECTRATIO_XMAXYMID: "constant",
    SVG_PRESERVEASPECTRATIO_XMAXYMIN: "constant",
    SVG_PRESERVEASPECTRATIO_XMIDYMAX: "constant",
    SVG_PRESERVEASPECTRATIO_XMIDYMID: "constant",
    SVG_PRESERVEASPECTRATIO_XMIDYMIN: "constant",
    SVG_PRESERVEASPECTRATIO_XMINYMAX: "constant",
    SVG_PRESERVEASPECTRATIO_XMINYMID: "constant",
    SVG_PRESERVEASPECTRATIO_XMINYMIN: "constant",
  }),
  ...bc("SVGRect", {
    fromRect: "func",
  }),
  ...bc("SVGTextContentElement", {
    LENGTHADJUST_SPACING: "constant",
    LENGTHADJUST_SPACINGANDGLYPHS: "constant",
    LENGTHADJUST_UNKNOWN: "constant",
  }),
  ...bc("SVGTextPathElement", {
    TEXTPATH_METHODTYPE_ALIGN: "constant",
    TEXTPATH_METHODTYPE_STRETCH: "constant",
    TEXTPATH_METHODTYPE_UNKNOWN: "constant",
    TEXTPATH_SPACINGTYPE_AUTO: "constant",
    TEXTPATH_SPACINGTYPE_EXACT: "constant",
    TEXTPATH_SPACINGTYPE_UNKNOWN: "constant",
  }),
  ...bc("SVGTransform", {
    SVG_TRANSFORM_MATRIX: "constant",
    SVG_TRANSFORM_ROTATE: "constant",
    SVG_TRANSFORM_SCALE: "constant",
    SVG_TRANSFORM_SKEWX: "constant",
    SVG_TRANSFORM_SKEWY: "constant",
    SVG_TRANSFORM_TRANSLATE: "constant",
    SVG_TRANSFORM_UNKNOWN: "constant",
  }),
  ...bc("SVGUnitTypes", {
    SVG_UNIT_TYPE_OBJECTBOUNDINGBOX: "constant",
    SVG_UNIT_TYPE_UNKNOWN: "constant",
    SVG_UNIT_TYPE_USERSPACEONUSE: "constant",
  }),
  SyntaxError: "noop",
  TypeError: "noop",
  ...sc("Uint16Array"),
  ...sc("Uint32Array"),
  ...sc("Uint8Array"),
  ...sc("Uint8ClampedArray"),
  URIError: "noop",
  URL: "noop",
  URLSearchParams: "noop",
  ...bc("WebGL2RenderingContext", {
    ACTIVE_UNIFORM_BLOCKS: "constant",
    ALREADY_SIGNALED: "constant",
    ANY_SAMPLES_PASSED: "constant",
    ANY_SAMPLES_PASSED_CONSERVATIVE: "constant",
    COLOR: "constant",
    COLOR_ATTACHMENT1: "constant",
    COLOR_ATTACHMENT10: "constant",
    COLOR_ATTACHMENT11: "constant",
    COLOR_ATTACHMENT12: "constant",
    COLOR_ATTACHMENT13: "constant",
    COLOR_ATTACHMENT14: "constant",
    COLOR_ATTACHMENT15: "constant",
    COLOR_ATTACHMENT2: "constant",
    COLOR_ATTACHMENT3: "constant",
    COLOR_ATTACHMENT4: "constant",
    COLOR_ATTACHMENT5: "constant",
    COLOR_ATTACHMENT6: "constant",
    COLOR_ATTACHMENT7: "constant",
    COLOR_ATTACHMENT8: "constant",
    COLOR_ATTACHMENT9: "constant",
    COMPARE_REF_TO_TEXTURE: "constant",
    CONDITION_SATISFIED: "constant",
    COPY_READ_BUFFER: "constant",
    COPY_READ_BUFFER_BINDING: "constant",
    COPY_WRITE_BUFFER: "constant",
    COPY_WRITE_BUFFER_BINDING: "constant",
    CURRENT_QUERY: "constant",
    DEPTH: "constant",
    DEPTH24_STENCIL8: "constant",
    DEPTH32F_STENCIL8: "constant",
    DEPTH_COMPONENT24: "constant",
    DEPTH_COMPONENT32F: "constant",
    DRAW_BUFFER0: "constant",
    DRAW_BUFFER1: "constant",
    DRAW_BUFFER10: "constant",
    DRAW_BUFFER11: "constant",
    DRAW_BUFFER12: "constant",
    DRAW_BUFFER13: "constant",
    DRAW_BUFFER14: "constant",
    DRAW_BUFFER15: "constant",
    DRAW_BUFFER2: "constant",
    DRAW_BUFFER3: "constant",
    DRAW_BUFFER4: "constant",
    DRAW_BUFFER5: "constant",
    DRAW_BUFFER6: "constant",
    DRAW_BUFFER7: "constant",
    DRAW_BUFFER8: "constant",
    DRAW_BUFFER9: "constant",
    DRAW_FRAMEBUFFER: "constant",
    DRAW_FRAMEBUFFER_BINDING: "constant",
    DYNAMIC_COPY: "constant",
    DYNAMIC_READ: "constant",
    FLOAT_32_UNSIGNED_INT_24_8_REV: "constant",
    FLOAT_MAT2x3: "constant",
    FLOAT_MAT2x4: "constant",
    FLOAT_MAT3x2: "constant",
    FLOAT_MAT3x4: "constant",
    FLOAT_MAT4x2: "constant",
    FLOAT_MAT4x3: "constant",
    FRAGMENT_SHADER_DERIVATIVE_HINT: "constant",
    FRAMEBUFFER_ATTACHMENT_ALPHA_SIZE: "constant",
    FRAMEBUFFER_ATTACHMENT_BLUE_SIZE: "constant",
    FRAMEBUFFER_ATTACHMENT_COLOR_ENCODING: "constant",
    FRAMEBUFFER_ATTACHMENT_COMPONENT_TYPE: "constant",
    FRAMEBUFFER_ATTACHMENT_DEPTH_SIZE: "constant",
    FRAMEBUFFER_ATTACHMENT_GREEN_SIZE: "constant",
    FRAMEBUFFER_ATTACHMENT_RED_SIZE: "constant",
    FRAMEBUFFER_ATTACHMENT_STENCIL_SIZE: "constant",
    FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER: "constant",
    FRAMEBUFFER_DEFAULT: "constant",
    FRAMEBUFFER_INCOMPLETE_MULTISAMPLE: "constant",
    HALF_FLOAT: "constant",
    INTERLEAVED_ATTRIBS: "constant",
    INT_2_10_10_10_REV: "constant",
    INT_SAMPLER_2D: "constant",
    INT_SAMPLER_2D_ARRAY: "constant",
    INT_SAMPLER_3D: "constant",
    INT_SAMPLER_CUBE: "constant",
    INVALID_INDEX: "constant",
    MAX: "constant",
    MAX_3D_TEXTURE_SIZE: "constant",
    MAX_ARRAY_TEXTURE_LAYERS: "constant",
    MAX_CLIENT_WAIT_TIMEOUT_WEBGL: "constant",
    MAX_COLOR_ATTACHMENTS: "constant",
    MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS: "constant",
    MAX_COMBINED_UNIFORM_BLOCKS: "constant",
    MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS: "constant",
    MAX_DRAW_BUFFERS: "constant",
    MAX_ELEMENTS_INDICES: "constant",
    MAX_ELEMENTS_VERTICES: "constant",
    MAX_ELEMENT_INDEX: "constant",
    MAX_FRAGMENT_INPUT_COMPONENTS: "constant",
    MAX_FRAGMENT_UNIFORM_BLOCKS: "constant",
    MAX_FRAGMENT_UNIFORM_COMPONENTS: "constant",
    MAX_PROGRAM_TEXEL_OFFSET: "constant",
    MAX_SAMPLES: "constant",
    MAX_SERVER_WAIT_TIMEOUT: "constant",
    MAX_TEXTURE_LOD_BIAS: "constant",
    MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS: "constant",
    MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS: "constant",
    MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS: "constant",
    MAX_UNIFORM_BLOCK_SIZE: "constant",
    MAX_UNIFORM_BUFFER_BINDINGS: "constant",
    MAX_VARYING_COMPONENTS: "constant",
    MAX_VERTEX_OUTPUT_COMPONENTS: "constant",
    MAX_VERTEX_UNIFORM_BLOCKS: "constant",
    MAX_VERTEX_UNIFORM_COMPONENTS: "constant",
    MIN: "constant",
    MIN_PROGRAM_TEXEL_OFFSET: "constant",
    OBJECT_TYPE: "constant",
    PACK_ROW_LENGTH: "constant",
    PACK_SKIP_PIXELS: "constant",
    PACK_SKIP_ROWS: "constant",
    PIXEL_PACK_BUFFER: "constant",
    PIXEL_PACK_BUFFER_BINDING: "constant",
    PIXEL_UNPACK_BUFFER: "constant",
    PIXEL_UNPACK_BUFFER_BINDING: "constant",
    QUERY_RESULT: "constant",
    QUERY_RESULT_AVAILABLE: "constant",
    R11F_G11F_B10F: "constant",
    R16F: "constant",
    R16I: "constant",
    R16UI: "constant",
    R32F: "constant",
    R32I: "constant",
    R32UI: "constant",
    R8: "constant",
    R8I: "constant",
    R8UI: "constant",
    R8_SNORM: "constant",
    RASTERIZER_DISCARD: "constant",
    READ_BUFFER: "constant",
    READ_FRAMEBUFFER: "constant",
    READ_FRAMEBUFFER_BINDING: "constant",
    RED: "constant",
    RED_INTEGER: "constant",
    RENDERBUFFER_SAMPLES: "constant",
    RG: "constant",
    RG16F: "constant",
    RG16I: "constant",
    RG16UI: "constant",
    RG32F: "constant",
    RG32I: "constant",
    RG32UI: "constant",
    RG8: "constant",
    RG8I: "constant",
    RG8UI: "constant",
    RG8_SNORM: "constant",
    RGB10_A2: "constant",
    RGB10_A2UI: "constant",
    RGB16F: "constant",
    RGB16I: "constant",
    RGB16UI: "constant",
    RGB32F: "constant",
    RGB32I: "constant",
    RGB32UI: "constant",
    RGB8: "constant",
    RGB8I: "constant",
    RGB8UI: "constant",
    RGB8_SNORM: "constant",
    RGB9_E5: "constant",
    RGBA16F: "constant",
    RGBA16I: "constant",
    RGBA16UI: "constant",
    RGBA32F: "constant",
    RGBA32I: "constant",
    RGBA32UI: "constant",
    RGBA8: "constant",
    RGBA8I: "constant",
    RGBA8UI: "constant",
    RGBA8_SNORM: "constant",
    RGBA_INTEGER: "constant",
    RGB_INTEGER: "constant",
    RG_INTEGER: "constant",
    SAMPLER_2D_ARRAY: "constant",
    SAMPLER_2D_ARRAY_SHADOW: "constant",
    SAMPLER_2D_SHADOW: "constant",
    SAMPLER_3D: "constant",
    SAMPLER_BINDING: "constant",
    SAMPLER_CUBE_SHADOW: "constant",
    SEPARATE_ATTRIBS: "constant",
    SIGNALED: "constant",
    SIGNED_NORMALIZED: "constant",
    SRGB: "constant",
    SRGB8: "constant",
    SRGB8_ALPHA8: "constant",
    STATIC_COPY: "constant",
    STATIC_READ: "constant",
    STENCIL: "constant",
    STREAM_COPY: "constant",
    STREAM_READ: "constant",
    SYNC_CONDITION: "constant",
    SYNC_FENCE: "constant",
    SYNC_FLAGS: "constant",
    SYNC_FLUSH_COMMANDS_BIT: "constant",
    SYNC_GPU_COMMANDS_COMPLETE: "constant",
    SYNC_STATUS: "constant",
    TEXTURE_2D_ARRAY: "constant",
    TEXTURE_3D: "constant",
    TEXTURE_BASE_LEVEL: "constant",
    TEXTURE_BINDING_2D_ARRAY: "constant",
    TEXTURE_BINDING_3D: "constant",
    TEXTURE_COMPARE_FUNC: "constant",
    TEXTURE_COMPARE_MODE: "constant",
    TEXTURE_IMMUTABLE_FORMAT: "constant",
    TEXTURE_IMMUTABLE_LEVELS: "constant",
    TEXTURE_MAX_LEVEL: "constant",
    TEXTURE_MAX_LOD: "constant",
    TEXTURE_MIN_LOD: "constant",
    TEXTURE_WRAP_R: "constant",
    TIMEOUT_EXPIRED: "constant",
    TIMEOUT_IGNORED: "constant",
    TRANSFORM_FEEDBACK: "constant",
    TRANSFORM_FEEDBACK_ACTIVE: "constant",
    TRANSFORM_FEEDBACK_BINDING: "constant",
    TRANSFORM_FEEDBACK_BUFFER: "constant",
    TRANSFORM_FEEDBACK_BUFFER_BINDING: "constant",
    TRANSFORM_FEEDBACK_BUFFER_MODE: "constant",
    TRANSFORM_FEEDBACK_BUFFER_SIZE: "constant",
    TRANSFORM_FEEDBACK_BUFFER_START: "constant",
    TRANSFORM_FEEDBACK_PAUSED: "constant",
    TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN: "constant",
    TRANSFORM_FEEDBACK_VARYINGS: "constant",
    UNIFORM_ARRAY_STRIDE: "constant",
    UNIFORM_BLOCK_ACTIVE_UNIFORMS: "constant",
    UNIFORM_BLOCK_ACTIVE_UNIFORM_INDICES: "constant",
    UNIFORM_BLOCK_BINDING: "constant",
    UNIFORM_BLOCK_DATA_SIZE: "constant",
    UNIFORM_BLOCK_INDEX: "constant",
    UNIFORM_BLOCK_REFERENCED_BY_FRAGMENT_SHADER: "constant",
    UNIFORM_BLOCK_REFERENCED_BY_VERTEX_SHADER: "constant",
    UNIFORM_BUFFER: "constant",
    UNIFORM_BUFFER_BINDING: "constant",
    UNIFORM_BUFFER_OFFSET_ALIGNMENT: "constant",
    UNIFORM_BUFFER_SIZE: "constant",
    UNIFORM_BUFFER_START: "constant",
    UNIFORM_IS_ROW_MAJOR: "constant",
    UNIFORM_MATRIX_STRIDE: "constant",
    UNIFORM_OFFSET: "constant",
    UNIFORM_SIZE: "constant",
    UNIFORM_TYPE: "constant",
    UNPACK_IMAGE_HEIGHT: "constant",
    UNPACK_ROW_LENGTH: "constant",
    UNPACK_SKIP_IMAGES: "constant",
    UNPACK_SKIP_PIXELS: "constant",
    UNPACK_SKIP_ROWS: "constant",
    UNSIGNALED: "constant",
    UNSIGNED_INT_10F_11F_11F_REV: "constant",
    UNSIGNED_INT_24_8: "constant",
    UNSIGNED_INT_2_10_10_10_REV: "constant",
    UNSIGNED_INT_5_9_9_9_REV: "constant",
    UNSIGNED_INT_SAMPLER_2D: "constant",
    UNSIGNED_INT_SAMPLER_2D_ARRAY: "constant",
    UNSIGNED_INT_SAMPLER_3D: "constant",
    UNSIGNED_INT_SAMPLER_CUBE: "constant",
    UNSIGNED_INT_VEC2: "constant",
    UNSIGNED_INT_VEC3: "constant",
    UNSIGNED_INT_VEC4: "constant",
    UNSIGNED_NORMALIZED: "constant",
    VERTEX_ARRAY_BINDING: "constant",
    VERTEX_ATTRIB_ARRAY_DIVISOR: "constant",
    VERTEX_ATTRIB_ARRAY_INTEGER: "constant",
    WAIT_FAILED: "constant",
    ACTIVE_ATTRIBUTES: "constant",
    ACTIVE_TEXTURE: "constant",
    ACTIVE_UNIFORMS: "constant",
    ALIASED_LINE_WIDTH_RANGE: "constant",
    ALIASED_POINT_SIZE_RANGE: "constant",
    ALPHA: "constant",
    ALPHA_BITS: "constant",
    ALWAYS: "constant",
    ARRAY_BUFFER: "constant",
    ARRAY_BUFFER_BINDING: "constant",
    ATTACHED_SHADERS: "constant",
    BACK: "constant",
    BLEND: "constant",
    BLEND_COLOR: "constant",
    BLEND_DST_ALPHA: "constant",
    BLEND_DST_RGB: "constant",
    BLEND_EQUATION: "constant",
    BLEND_EQUATION_ALPHA: "constant",
    BLEND_EQUATION_RGB: "constant",
    BLEND_SRC_ALPHA: "constant",
    BLEND_SRC_RGB: "constant",
    BLUE_BITS: "constant",
    BOOL: "constant",
    BOOL_VEC2: "constant",
    BOOL_VEC3: "constant",
    BOOL_VEC4: "constant",
    BROWSER_DEFAULT_WEBGL: "constant",
    BUFFER_SIZE: "constant",
    BUFFER_USAGE: "constant",
    BYTE: "constant",
    CCW: "constant",
    CLAMP_TO_EDGE: "constant",
    COLOR_ATTACHMENT0: "constant",
    COLOR_BUFFER_BIT: "constant",
    COLOR_CLEAR_VALUE: "constant",
    COLOR_WRITEMASK: "constant",
    COMPILE_STATUS: "constant",
    COMPRESSED_TEXTURE_FORMATS: "constant",
    CONSTANT_ALPHA: "constant",
    CONSTANT_COLOR: "constant",
    CONTEXT_LOST_WEBGL: "constant",
    CULL_FACE: "constant",
    CULL_FACE_MODE: "constant",
    CURRENT_PROGRAM: "constant",
    CURRENT_VERTEX_ATTRIB: "constant",
    CW: "constant",
    DECR: "constant",
    DECR_WRAP: "constant",
    DELETE_STATUS: "constant",
    DEPTH_ATTACHMENT: "constant",
    DEPTH_BITS: "constant",
    DEPTH_BUFFER_BIT: "constant",
    DEPTH_CLEAR_VALUE: "constant",
    DEPTH_COMPONENT: "constant",
    DEPTH_COMPONENT16: "constant",
    DEPTH_FUNC: "constant",
    DEPTH_RANGE: "constant",
    DEPTH_STENCIL: "constant",
    DEPTH_STENCIL_ATTACHMENT: "constant",
    DEPTH_TEST: "constant",
    DEPTH_WRITEMASK: "constant",
    DITHER: "constant",
    DONT_CARE: "constant",
    DST_ALPHA: "constant",
    DST_COLOR: "constant",
    DYNAMIC_DRAW: "constant",
    ELEMENT_ARRAY_BUFFER: "constant",
    ELEMENT_ARRAY_BUFFER_BINDING: "constant",
    EQUAL: "constant",
    FASTEST: "constant",
    FLOAT: "constant",
    FLOAT_MAT2: "constant",
    FLOAT_MAT3: "constant",
    FLOAT_MAT4: "constant",
    FLOAT_VEC2: "constant",
    FLOAT_VEC3: "constant",
    FLOAT_VEC4: "constant",
    FRAGMENT_SHADER: "constant",
    FRAMEBUFFER: "constant",
    FRAMEBUFFER_ATTACHMENT_OBJECT_NAME: "constant",
    FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE: "constant",
    FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE: "constant",
    FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL: "constant",
    FRAMEBUFFER_BINDING: "constant",
    FRAMEBUFFER_COMPLETE: "constant",
    FRAMEBUFFER_INCOMPLETE_ATTACHMENT: "constant",
    FRAMEBUFFER_INCOMPLETE_DIMENSIONS: "constant",
    FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT: "constant",
    FRAMEBUFFER_UNSUPPORTED: "constant",
    FRONT: "constant",
    FRONT_AND_BACK: "constant",
    FRONT_FACE: "constant",
    FUNC_ADD: "constant",
    FUNC_REVERSE_SUBTRACT: "constant",
    FUNC_SUBTRACT: "constant",
    GENERATE_MIPMAP_HINT: "constant",
    GEQUAL: "constant",
    GREATER: "constant",
    GREEN_BITS: "constant",
    HIGH_FLOAT: "constant",
    HIGH_INT: "constant",
    IMPLEMENTATION_COLOR_READ_FORMAT: "constant",
    IMPLEMENTATION_COLOR_READ_TYPE: "constant",
    INCR: "constant",
    INCR_WRAP: "constant",
    INT: "constant",
    INT_VEC2: "constant",
    INT_VEC3: "constant",
    INT_VEC4: "constant",
    INVALID_ENUM: "constant",
    INVALID_FRAMEBUFFER_OPERATION: "constant",
    INVALID_OPERATION: "constant",
    INVALID_VALUE: "constant",
    INVERT: "constant",
    KEEP: "constant",
    LEQUAL: "constant",
    LESS: "constant",
    LINEAR: "constant",
    LINEAR_MIPMAP_LINEAR: "constant",
    LINEAR_MIPMAP_NEAREST: "constant",
    LINES: "constant",
    LINE_LOOP: "constant",
    LINE_STRIP: "constant",
    LINE_WIDTH: "constant",
    LINK_STATUS: "constant",
    LOW_FLOAT: "constant",
    LOW_INT: "constant",
    LUMINANCE: "constant",
    LUMINANCE_ALPHA: "constant",
    MAX_COMBINED_TEXTURE_IMAGE_UNITS: "constant",
    MAX_CUBE_MAP_TEXTURE_SIZE: "constant",
    MAX_FRAGMENT_UNIFORM_VECTORS: "constant",
    MAX_RENDERBUFFER_SIZE: "constant",
    MAX_TEXTURE_IMAGE_UNITS: "constant",
    MAX_TEXTURE_SIZE: "constant",
    MAX_VARYING_VECTORS: "constant",
    MAX_VERTEX_ATTRIBS: "constant",
    MAX_VERTEX_TEXTURE_IMAGE_UNITS: "constant",
    MAX_VERTEX_UNIFORM_VECTORS: "constant",
    MAX_VIEWPORT_DIMS: "constant",
    MEDIUM_FLOAT: "constant",
    MEDIUM_INT: "constant",
    MIRRORED_REPEAT: "constant",
    NEAREST: "constant",
    NEAREST_MIPMAP_LINEAR: "constant",
    NEAREST_MIPMAP_NEAREST: "constant",
    NEVER: "constant",
    NICEST: "constant",
    NONE: "constant",
    NOTEQUAL: "constant",
    NO_ERROR: "constant",
    ONE: "constant",
    ONE_MINUS_CONSTANT_ALPHA: "constant",
    ONE_MINUS_CONSTANT_COLOR: "constant",
    ONE_MINUS_DST_ALPHA: "constant",
    ONE_MINUS_DST_COLOR: "constant",
    ONE_MINUS_SRC_ALPHA: "constant",
    ONE_MINUS_SRC_COLOR: "constant",
    OUT_OF_MEMORY: "constant",
    PACK_ALIGNMENT: "constant",
    POINTS: "constant",
    POLYGON_OFFSET_FACTOR: "constant",
    POLYGON_OFFSET_FILL: "constant",
    POLYGON_OFFSET_UNITS: "constant",
    RED_BITS: "constant",
    RENDERBUFFER: "constant",
    RENDERBUFFER_ALPHA_SIZE: "constant",
    RENDERBUFFER_BINDING: "constant",
    RENDERBUFFER_BLUE_SIZE: "constant",
    RENDERBUFFER_DEPTH_SIZE: "constant",
    RENDERBUFFER_GREEN_SIZE: "constant",
    RENDERBUFFER_HEIGHT: "constant",
    RENDERBUFFER_INTERNAL_FORMAT: "constant",
    RENDERBUFFER_RED_SIZE: "constant",
    RENDERBUFFER_STENCIL_SIZE: "constant",
    RENDERBUFFER_WIDTH: "constant",
    RENDERER: "constant",
    REPEAT: "constant",
    REPLACE: "constant",
    RGB: "constant",
    RGB565: "constant",
    RGB5_A1: "constant",
    RGBA: "constant",
    RGBA4: "constant",
    SAMPLER_2D: "constant",
    SAMPLER_CUBE: "constant",
    SAMPLES: "constant",
    SAMPLE_ALPHA_TO_COVERAGE: "constant",
    SAMPLE_BUFFERS: "constant",
    SAMPLE_COVERAGE: "constant",
    SAMPLE_COVERAGE_INVERT: "constant",
    SAMPLE_COVERAGE_VALUE: "constant",
    SCISSOR_BOX: "constant",
    SCISSOR_TEST: "constant",
    SHADER_TYPE: "constant",
    SHADING_LANGUAGE_VERSION: "constant",
    SHORT: "constant",
    SRC_ALPHA: "constant",
    SRC_ALPHA_SATURATE: "constant",
    SRC_COLOR: "constant",
    STATIC_DRAW: "constant",
    STENCIL_ATTACHMENT: "constant",
    STENCIL_BACK_FAIL: "constant",
    STENCIL_BACK_FUNC: "constant",
    STENCIL_BACK_PASS_DEPTH_FAIL: "constant",
    STENCIL_BACK_PASS_DEPTH_PASS: "constant",
    STENCIL_BACK_REF: "constant",
    STENCIL_BACK_VALUE_MASK: "constant",
    STENCIL_BACK_WRITEMASK: "constant",
    STENCIL_BITS: "constant",
    STENCIL_BUFFER_BIT: "constant",
    STENCIL_CLEAR_VALUE: "constant",
    STENCIL_FAIL: "constant",
    STENCIL_FUNC: "constant",
    STENCIL_INDEX8: "constant",
    STENCIL_PASS_DEPTH_FAIL: "constant",
    STENCIL_PASS_DEPTH_PASS: "constant",
    STENCIL_REF: "constant",
    STENCIL_TEST: "constant",
    STENCIL_VALUE_MASK: "constant",
    STENCIL_WRITEMASK: "constant",
    STREAM_DRAW: "constant",
    SUBPIXEL_BITS: "constant",
    TEXTURE: "constant",
    TEXTURE0: "constant",
    TEXTURE1: "constant",
    TEXTURE10: "constant",
    TEXTURE11: "constant",
    TEXTURE12: "constant",
    TEXTURE13: "constant",
    TEXTURE14: "constant",
    TEXTURE15: "constant",
    TEXTURE16: "constant",
    TEXTURE17: "constant",
    TEXTURE18: "constant",
    TEXTURE19: "constant",
    TEXTURE2: "constant",
    TEXTURE20: "constant",
    TEXTURE21: "constant",
    TEXTURE22: "constant",
    TEXTURE23: "constant",
    TEXTURE24: "constant",
    TEXTURE25: "constant",
    TEXTURE26: "constant",
    TEXTURE27: "constant",
    TEXTURE28: "constant",
    TEXTURE29: "constant",
    TEXTURE3: "constant",
    TEXTURE30: "constant",
    TEXTURE31: "constant",
    TEXTURE4: "constant",
    TEXTURE5: "constant",
    TEXTURE6: "constant",
    TEXTURE7: "constant",
    TEXTURE8: "constant",
    TEXTURE9: "constant",
    TEXTURE_2D: "constant",
    TEXTURE_BINDING_2D: "constant",
    TEXTURE_BINDING_CUBE_MAP: "constant",
    TEXTURE_CUBE_MAP: "constant",
    TEXTURE_CUBE_MAP_NEGATIVE_X: "constant",
    TEXTURE_CUBE_MAP_NEGATIVE_Y: "constant",
    TEXTURE_CUBE_MAP_NEGATIVE_Z: "constant",
    TEXTURE_CUBE_MAP_POSITIVE_X: "constant",
    TEXTURE_CUBE_MAP_POSITIVE_Y: "constant",
    TEXTURE_CUBE_MAP_POSITIVE_Z: "constant",
    TEXTURE_MAG_FILTER: "constant",
    TEXTURE_MIN_FILTER: "constant",
    TEXTURE_WRAP_S: "constant",
    TEXTURE_WRAP_T: "constant",
    TRIANGLES: "constant",
    TRIANGLE_FAN: "constant",
    TRIANGLE_STRIP: "constant",
    UNPACK_ALIGNMENT: "constant",
    UNPACK_COLORSPACE_CONVERSION_WEBGL: "constant",
    UNPACK_FLIP_Y_WEBGL: "constant",
    UNPACK_PREMULTIPLY_ALPHA_WEBGL: "constant",
    UNSIGNED_BYTE: "constant",
    UNSIGNED_INT: "constant",
    UNSIGNED_SHORT: "constant",
    UNSIGNED_SHORT_4_4_4_4: "constant",
    UNSIGNED_SHORT_5_5_5_1: "constant",
    UNSIGNED_SHORT_5_6_5: "constant",
    VALIDATE_STATUS: "constant",
    VENDOR: "constant",
    VERSION: "constant",
    VERTEX_ATTRIB_ARRAY_BUFFER_BINDING: "constant",
    VERTEX_ATTRIB_ARRAY_ENABLED: "constant",
    VERTEX_ATTRIB_ARRAY_NORMALIZED: "constant",
    VERTEX_ATTRIB_ARRAY_POINTER: "constant",
    VERTEX_ATTRIB_ARRAY_SIZE: "constant",
    VERTEX_ATTRIB_ARRAY_STRIDE: "constant",
    VERTEX_ATTRIB_ARRAY_TYPE: "constant",
    VERTEX_SHADER: "constant",
    VIEWPORT: "constant",
    ZERO: "constant",
  }),
  ...bc("WebGLRenderingContext", {
    ACTIVE_ATTRIBUTES: "constant",
    ACTIVE_TEXTURE: "constant",
    ACTIVE_UNIFORMS: "constant",
    ALIASED_LINE_WIDTH_RANGE: "constant",
    ALIASED_POINT_SIZE_RANGE: "constant",
    ALPHA: "constant",
    ALPHA_BITS: "constant",
    ALWAYS: "constant",
    ARRAY_BUFFER: "constant",
    ARRAY_BUFFER_BINDING: "constant",
    ATTACHED_SHADERS: "constant",
    BACK: "constant",
    BLEND: "constant",
    BLEND_COLOR: "constant",
    BLEND_DST_ALPHA: "constant",
    BLEND_DST_RGB: "constant",
    BLEND_EQUATION: "constant",
    BLEND_EQUATION_ALPHA: "constant",
    BLEND_EQUATION_RGB: "constant",
    BLEND_SRC_ALPHA: "constant",
    BLEND_SRC_RGB: "constant",
    BLUE_BITS: "constant",
    BOOL: "constant",
    BOOL_VEC2: "constant",
    BOOL_VEC3: "constant",
    BOOL_VEC4: "constant",
    BROWSER_DEFAULT_WEBGL: "constant",
    BUFFER_SIZE: "constant",
    BUFFER_USAGE: "constant",
    BYTE: "constant",
    CCW: "constant",
    CLAMP_TO_EDGE: "constant",
    COLOR_ATTACHMENT0: "constant",
    COLOR_BUFFER_BIT: "constant",
    COLOR_CLEAR_VALUE: "constant",
    COLOR_WRITEMASK: "constant",
    COMPILE_STATUS: "constant",
    COMPRESSED_TEXTURE_FORMATS: "constant",
    CONSTANT_ALPHA: "constant",
    CONSTANT_COLOR: "constant",
    CONTEXT_LOST_WEBGL: "constant",
    CULL_FACE: "constant",
    CULL_FACE_MODE: "constant",
    CURRENT_PROGRAM: "constant",
    CURRENT_VERTEX_ATTRIB: "constant",
    CW: "constant",
    DECR: "constant",
    DECR_WRAP: "constant",
    DELETE_STATUS: "constant",
    DEPTH_ATTACHMENT: "constant",
    DEPTH_BITS: "constant",
    DEPTH_BUFFER_BIT: "constant",
    DEPTH_CLEAR_VALUE: "constant",
    DEPTH_COMPONENT: "constant",
    DEPTH_COMPONENT16: "constant",
    DEPTH_FUNC: "constant",
    DEPTH_RANGE: "constant",
    DEPTH_STENCIL: "constant",
    DEPTH_STENCIL_ATTACHMENT: "constant",
    DEPTH_TEST: "constant",
    DEPTH_WRITEMASK: "constant",
    DITHER: "constant",
    DONT_CARE: "constant",
    DST_ALPHA: "constant",
    DST_COLOR: "constant",
    DYNAMIC_DRAW: "constant",
    ELEMENT_ARRAY_BUFFER: "constant",
    ELEMENT_ARRAY_BUFFER_BINDING: "constant",
    EQUAL: "constant",
    FASTEST: "constant",
    FLOAT: "constant",
    FLOAT_MAT2: "constant",
    FLOAT_MAT3: "constant",
    FLOAT_MAT4: "constant",
    FLOAT_VEC2: "constant",
    FLOAT_VEC3: "constant",
    FLOAT_VEC4: "constant",
    FRAGMENT_SHADER: "constant",
    FRAMEBUFFER: "constant",
    FRAMEBUFFER_ATTACHMENT_OBJECT_NAME: "constant",
    FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE: "constant",
    FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE: "constant",
    FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL: "constant",
    FRAMEBUFFER_BINDING: "constant",
    FRAMEBUFFER_COMPLETE: "constant",
    FRAMEBUFFER_INCOMPLETE_ATTACHMENT: "constant",
    FRAMEBUFFER_INCOMPLETE_DIMENSIONS: "constant",
    FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT: "constant",
    FRAMEBUFFER_UNSUPPORTED: "constant",
    FRONT: "constant",
    FRONT_AND_BACK: "constant",
    FRONT_FACE: "constant",
    FUNC_ADD: "constant",
    FUNC_REVERSE_SUBTRACT: "constant",
    FUNC_SUBTRACT: "constant",
    GENERATE_MIPMAP_HINT: "constant",
    GEQUAL: "constant",
    GREATER: "constant",
    GREEN_BITS: "constant",
    HIGH_FLOAT: "constant",
    HIGH_INT: "constant",
    IMPLEMENTATION_COLOR_READ_FORMAT: "constant",
    IMPLEMENTATION_COLOR_READ_TYPE: "constant",
    INCR: "constant",
    INCR_WRAP: "constant",
    INT: "constant",
    INT_VEC2: "constant",
    INT_VEC3: "constant",
    INT_VEC4: "constant",
    INVALID_ENUM: "constant",
    INVALID_FRAMEBUFFER_OPERATION: "constant",
    INVALID_OPERATION: "constant",
    INVALID_VALUE: "constant",
    INVERT: "constant",
    KEEP: "constant",
    LEQUAL: "constant",
    LESS: "constant",
    LINEAR: "constant",
    LINEAR_MIPMAP_LINEAR: "constant",
    LINEAR_MIPMAP_NEAREST: "constant",
    LINES: "constant",
    LINE_LOOP: "constant",
    LINE_STRIP: "constant",
    LINE_WIDTH: "constant",
    LINK_STATUS: "constant",
    LOW_FLOAT: "constant",
    LOW_INT: "constant",
    LUMINANCE: "constant",
    LUMINANCE_ALPHA: "constant",
    MAX_COMBINED_TEXTURE_IMAGE_UNITS: "constant",
    MAX_CUBE_MAP_TEXTURE_SIZE: "constant",
    MAX_FRAGMENT_UNIFORM_VECTORS: "constant",
    MAX_RENDERBUFFER_SIZE: "constant",
    MAX_TEXTURE_IMAGE_UNITS: "constant",
    MAX_TEXTURE_SIZE: "constant",
    MAX_VARYING_VECTORS: "constant",
    MAX_VERTEX_ATTRIBS: "constant",
    MAX_VERTEX_TEXTURE_IMAGE_UNITS: "constant",
    MAX_VERTEX_UNIFORM_VECTORS: "constant",
    MAX_VIEWPORT_DIMS: "constant",
    MEDIUM_FLOAT: "constant",
    MEDIUM_INT: "constant",
    MIRRORED_REPEAT: "constant",
    NEAREST: "constant",
    NEAREST_MIPMAP_LINEAR: "constant",
    NEAREST_MIPMAP_NEAREST: "constant",
    NEVER: "constant",
    NICEST: "constant",
    NONE: "constant",
    NOTEQUAL: "constant",
    NO_ERROR: "constant",
    ONE: "constant",
    ONE_MINUS_CONSTANT_ALPHA: "constant",
    ONE_MINUS_CONSTANT_COLOR: "constant",
    ONE_MINUS_DST_ALPHA: "constant",
    ONE_MINUS_DST_COLOR: "constant",
    ONE_MINUS_SRC_ALPHA: "constant",
    ONE_MINUS_SRC_COLOR: "constant",
    OUT_OF_MEMORY: "constant",
    PACK_ALIGNMENT: "constant",
    POINTS: "constant",
    POLYGON_OFFSET_FACTOR: "constant",
    POLYGON_OFFSET_FILL: "constant",
    POLYGON_OFFSET_UNITS: "constant",
    RED_BITS: "constant",
    RENDERBUFFER: "constant",
    RENDERBUFFER_ALPHA_SIZE: "constant",
    RENDERBUFFER_BINDING: "constant",
    RENDERBUFFER_BLUE_SIZE: "constant",
    RENDERBUFFER_DEPTH_SIZE: "constant",
    RENDERBUFFER_GREEN_SIZE: "constant",
    RENDERBUFFER_HEIGHT: "constant",
    RENDERBUFFER_INTERNAL_FORMAT: "constant",
    RENDERBUFFER_RED_SIZE: "constant",
    RENDERBUFFER_STENCIL_SIZE: "constant",
    RENDERBUFFER_WIDTH: "constant",
    RENDERER: "constant",
    REPEAT: "constant",
    REPLACE: "constant",
    RGB: "constant",
    RGB565: "constant",
    RGB5_A1: "constant",
    RGBA: "constant",
    RGBA4: "constant",
    SAMPLER_2D: "constant",
    SAMPLER_CUBE: "constant",
    SAMPLES: "constant",
    SAMPLE_ALPHA_TO_COVERAGE: "constant",
    SAMPLE_BUFFERS: "constant",
    SAMPLE_COVERAGE: "constant",
    SAMPLE_COVERAGE_INVERT: "constant",
    SAMPLE_COVERAGE_VALUE: "constant",
    SCISSOR_BOX: "constant",
    SCISSOR_TEST: "constant",
    SHADER_TYPE: "constant",
    SHADING_LANGUAGE_VERSION: "constant",
    SHORT: "constant",
    SRC_ALPHA: "constant",
    SRC_ALPHA_SATURATE: "constant",
    SRC_COLOR: "constant",
    STATIC_DRAW: "constant",
    STENCIL_ATTACHMENT: "constant",
    STENCIL_BACK_FAIL: "constant",
    STENCIL_BACK_FUNC: "constant",
    STENCIL_BACK_PASS_DEPTH_FAIL: "constant",
    STENCIL_BACK_PASS_DEPTH_PASS: "constant",
    STENCIL_BACK_REF: "constant",
    STENCIL_BACK_VALUE_MASK: "constant",
    STENCIL_BACK_WRITEMASK: "constant",
    STENCIL_BITS: "constant",
    STENCIL_BUFFER_BIT: "constant",
    STENCIL_CLEAR_VALUE: "constant",
    STENCIL_FAIL: "constant",
    STENCIL_FUNC: "constant",
    STENCIL_INDEX8: "constant",
    STENCIL_PASS_DEPTH_FAIL: "constant",
    STENCIL_PASS_DEPTH_PASS: "constant",
    STENCIL_REF: "constant",
    STENCIL_TEST: "constant",
    STENCIL_VALUE_MASK: "constant",
    STENCIL_WRITEMASK: "constant",
    STREAM_DRAW: "constant",
    SUBPIXEL_BITS: "constant",
    TEXTURE: "constant",
    TEXTURE0: "constant",
    TEXTURE1: "constant",
    TEXTURE10: "constant",
    TEXTURE11: "constant",
    TEXTURE12: "constant",
    TEXTURE13: "constant",
    TEXTURE14: "constant",
    TEXTURE15: "constant",
    TEXTURE16: "constant",
    TEXTURE17: "constant",
    TEXTURE18: "constant",
    TEXTURE19: "constant",
    TEXTURE2: "constant",
    TEXTURE20: "constant",
    TEXTURE21: "constant",
    TEXTURE22: "constant",
    TEXTURE23: "constant",
    TEXTURE24: "constant",
    TEXTURE25: "constant",
    TEXTURE26: "constant",
    TEXTURE27: "constant",
    TEXTURE28: "constant",
    TEXTURE29: "constant",
    TEXTURE3: "constant",
    TEXTURE30: "constant",
    TEXTURE31: "constant",
    TEXTURE4: "constant",
    TEXTURE5: "constant",
    TEXTURE6: "constant",
    TEXTURE7: "constant",
    TEXTURE8: "constant",
    TEXTURE9: "constant",
    TEXTURE_2D: "constant",
    TEXTURE_BINDING_2D: "constant",
    TEXTURE_BINDING_CUBE_MAP: "constant",
    TEXTURE_CUBE_MAP: "constant",
    TEXTURE_CUBE_MAP_NEGATIVE_X: "constant",
    TEXTURE_CUBE_MAP_NEGATIVE_Y: "constant",
    TEXTURE_CUBE_MAP_NEGATIVE_Z: "constant",
    TEXTURE_CUBE_MAP_POSITIVE_X: "constant",
    TEXTURE_CUBE_MAP_POSITIVE_Y: "constant",
    TEXTURE_CUBE_MAP_POSITIVE_Z: "constant",
    TEXTURE_MAG_FILTER: "constant",
    TEXTURE_MIN_FILTER: "constant",
    TEXTURE_WRAP_S: "constant",
    TEXTURE_WRAP_T: "constant",
    TRIANGLES: "constant",
    TRIANGLE_FAN: "constant",
    TRIANGLE_STRIP: "constant",
    UNPACK_ALIGNMENT: "constant",
    UNPACK_COLORSPACE_CONVERSION_WEBGL: "constant",
    UNPACK_FLIP_Y_WEBGL: "constant",
    UNPACK_PREMULTIPLY_ALPHA_WEBGL: "constant",
    UNSIGNED_BYTE: "constant",
    UNSIGNED_INT: "constant",
    UNSIGNED_SHORT: "constant",
    UNSIGNED_SHORT_4_4_4_4: "constant",
    UNSIGNED_SHORT_5_5_5_1: "constant",
    UNSIGNED_SHORT_5_6_5: "constant",
    VALIDATE_STATUS: "constant",
    VENDOR: "constant",
    VERSION: "constant",
    VERTEX_ATTRIB_ARRAY_BUFFER_BINDING: "constant",
    VERTEX_ATTRIB_ARRAY_ENABLED: "constant",
    VERTEX_ATTRIB_ARRAY_NORMALIZED: "constant",
    VERTEX_ATTRIB_ARRAY_POINTER: "constant",
    VERTEX_ATTRIB_ARRAY_SIZE: "constant",
    VERTEX_ATTRIB_ARRAY_STRIDE: "constant",
    VERTEX_ATTRIB_ARRAY_TYPE: "constant",
    VERTEX_SHADER: "constant",
    VIEWPORT: "constant",
    ZERO: "constant",
  }),
  ...bc("WebKitCSSMatrix", {
    fromFloat32Array: "func",
    fromFloat64Array: "func",
    fromMatrix: "func",
  }),
  ...bc("WebSocket", {
    CLOSED: "constant",
    CLOSING: "constant",
    CONNECTING: "constant",
    OPEN: "constant",
  }),
  ...bc("WheelEvent", {
    DOM_DELTA_LINE: "constant",
    DOM_DELTA_PAGE: "constant",
    DOM_DELTA_PIXEL: "constant",
  }),
  ...bc("XMLHttpRequest", {
    DONE: "constant",
    HEADERS_RECEIVED: "constant",
    LOADING: "constant",
    OPENED: "constant",
    UNSENT: "constant",
  }),
  ...bc("XPathResult", {
    ANY_TYPE: "constant",
    ANY_UNORDERED_NODE_TYPE: "constant",
    BOOLEAN_TYPE: "constant",
    FIRST_ORDERED_NODE_TYPE: "constant",
    NUMBER_TYPE: "constant",
    ORDERED_NODE_ITERATOR_TYPE: "constant",
    ORDERED_NODE_SNAPSHOT_TYPE: "constant",
    STRING_TYPE: "constant",
    UNORDERED_NODE_ITERATOR_TYPE: "constant",
    UNORDERED_NODE_SNAPSHOT_TYPE: "constant",
  }),
};
export const isGlobalCtor = (name: string): name is GlobalConstructorsWithStatic => {
  return name in globalConstructorWithStatics;
};
//*/
